#include "data.h"

const Point Data::DEFAULT_GAME_AREA_BOTTOM_LEFT=Point(0,0);
const Point Data::DEFAULT_GAME_AREA_TOP_RIGHT=Point(0,0);
const int Data::DEFAULT_FRAME_PER_SECOND=30;
const int Data::DEFAULT_MAX_LIFE=3;
const int Data::DEFAULT_MAX_HEALTH=100;

Data::Data():
    GAME_AREA_BOTTOM_LEFT(DEFAULT_GAME_AREA_BOTTOM_LEFT),
    GAME_AREA_TOP_RIGHT(DEFAULT_GAME_AREA_TOP_RIGHT),
    FRAME_PER_SECOND(DEFAULT_FRAME_PER_SECOND),
    MAX_LIFE(DEFAULT_MAX_LIFE),
    MAX_HEALTH(DEFAULT_MAX_HEALTH)
{
}
